---
confetti_for_assignments:
  type: setting
  state: hidden
  display_name: Confetti for On-Time Submissions
  description: |-
    Displays confetti for users that turn in an assignment prior
    to the set due date.
  applies_to: RootAccount

confetti_for_valid_links:
  type: setting
  state: hidden
  display_name: Confetti for valid links
  description: |-
    Displays confetti for teachers that run the link validator on
    a course and no issues are found.
  applies_to: RootAccount

react_discussions_post:
  state: hidden
  beta: true
  display_name: Discussions/Announcements Redesign
  description:
    wrapper: <a href="https://community.canvaslms.com/t5/Discussions-Announcements/gh-p/discussions">\1</a>
    discussion_redesign_description: This feature enhances the Canvas experience
      within Discussions and Announcements. When this flag is enabled, early access
      to ongoing improvements will be displayed automatically with every release.
      For full details, please see the *Discussions/Announcements Redesign user group*
      in the Canvas Community
  applies_to: Course

draft_discussions:
  state: hidden
  beta: false
  display_name: Draft Discussion Entries
  description: |-
    Will allow for saving drafts as students type their replies to a discussion topic
    in the discussions redesign
  applies_to: SiteAdmin

discussions_reporting:
  state: hidden
  beta: false
  display_name: Discussions Redesign - Reporting
  description: |-
    This feature flag enables Discussions Reporting inside the new
    Discussions Redesign work.
  applies_to: SiteAdmin

isolated_view:
  state: hidden
  beta: true
  display_name: Discussions Redesign - Isolated View
  description: |-
    This feature flag enables Isolated View inside the new
    Discussions Redesign work.
  applies_to: SiteAdmin

react_inbox:
  state: hidden
  display_name: Update Inbox page to use react/instui
  description: |-
    This refactor will make this page more maintainable
  applies_to: RootAccount

smart_alerts:
  state: hidden
  display_name: Smart alerts
  description: |-
    Notify students in time of assignments that require their attention.
  applies_to: RootAccount

show_push_notification_account_setting:
  state: hidden
  display_name: Allow push notification opt-out
  description: |-
    Enable an account setting which toggles push notifications for that account
  applies_to: SiteAdmin

apollo_caching:
  state: hidden
  display_name: Apollo caching
  description: |-
    Allow for Apollo to cache graphQL queries on a users browser to speed up their experience
  applies_to: SiteAdmin
