# do not create a queue: section for your test environment
test:
  adapter: postgresql
  encoding: utf8
  database: canvas
  host: localhost
  username: canvas
  password: 19990923
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: canvas
  password: 19990923
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: canvas
  host: localhost
  username: canvas
  password: 19990923
  timeout: 5000
